BUILD_STATUS_QUEUED = "queued"
BUILD_STATUS_RUNNING = "running"
BUILD_STATUS_SUCCESS = "success"
BUILD_STATUS_FAILED = "failed"

DEPLOY_STATUS_QUEUED = "queued"
DEPLOY_STATUS_RUNNING = "running"
DEPLOY_STATUS_SUCCESS = "success"
DEPLOY_STATUS_FAILED = "failed"

